apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb-uid
    url: timescaledb:5432
    user: stocks
    secureJsonData:
      password: stocks
    jsonData:
      database: stocks
      sslmode: disable
      timescaledb: true
      postgresVersion: 1500
    isDefault: true
